# Define dictionary of cities from the facebook marketplace directory for United States.
# https://m.facebook.com/marketplace/directory/US/?_se_imp=0oey5sMRMSl7wluQZ
# TODO - Add more cities to the dictionary.
CITIES = {
    'New York': 'nyc',
    'Los Angeles': 'la',
    'Las Vegas': 'vegas',
    'Chicago': 'chicago',
    'Houston': 'houston',
    'San Antonio': 'sanantonio',
    'Miami': 'miami',
    'Orlando': 'orlando',
    'San Diego': 'sandiego',
    'Arlington': 'arlington',
    'Balitmore': 'baltimore',
    'Cincinnati': 'cincinnati',
    'Denver': 'denver',
    'Fort Worth': 'fortworth',
    'Jacksonville': 'jacksonville',
    'Memphis': 'memphis',
    'Nashville': 'nashville',
    'Philadelphia': 'philly',
    'Portland': 'portland',
    'San Jose': 'sanjose',
    'Tucson': 'tucson',
    'Atlanta': 'atlanta',
    'Boston': 'boston',
    'Columnbus': 'columbus',
    'Detroit': 'detroit',
    'Honolulu': 'honolulu',
    'Kansas City': 'kansascity',
    'New Orleans': 'neworleans',
    'Phoenix': 'phoenix',
    'Seattle': 'seattle',
    'Washington DC': 'dc',
    'Milwaukee': 'milwaukee',
    'Sacremento': 'sac',
    'Austin': 'austin',
    'Charlotte': 'charlotte',
    'Dallas': 'dallas',
    'El Paso': 'elpaso',
    'Indianapolis': 'indianapolis',
    'Louisville': 'louisville',
    'Minneapolis': 'minneapolis',
    'Oaklahoma City' : 'oklahoma',
    'Pittsburgh': 'pittsburgh',
    'San Francisco': 'sanfrancisco',
    'Tampa': 'tampa',
}